sonar.projectKey=hello-world-cicd
sonar.projectName=hello-world-cicd
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.git/**,**/k8s/**,**/ansible/**,**/helm/**,**/*.md
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
